version: '3'

services:
  db:
    image: postgres:10.18-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - db:/var/lib/postgresql/data
  rails:
    image: chucksalem/oceano-backend
    depends_on:
      - db
    links:
      - db:db
    hostname: rails
    container_name: rails
    environment:
      RAILS_ENV: development
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
  nginx-proxy:
    image: jwilder/nginx-proxy
    links:
      - rails:rails
      - frontend:frontend
    ports:
      - 80:80
      - 443:443 
      - 5000:5000
      - 3000:3000
      - 3001:3001
    volumes:
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /etc/ssl/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
  frontend:
    image: chucksalem/oceano-frontend
    ports:
      - 3001:3001




volumes:
  db:
    driver: local
