Vagrant.configure(2) do |config|
    config.vm.box = "hashicorp/precise64"
    config.vm.network :private_network, ip: "192.168.2.100"
    config.vm.hostname = "oceano-local"

    config.ssh.forward_agent = true

    config.vm.provision :ansible do |ansible|
        ansible.sudo = true
        ansible.verbose = 'v'
        ansible.playbook = "playbooks/vagrant.yml"
        ansible.groups   = { "vagrant" => ["default"] }
    end
end
